const quizDB = [
  {
    qid: "1",
    question: "Q1: What is the fullform of HTML?",
    a: "Hi Text Markup Law",
    b: "Hello To My Land",
    c: "HyperText Markup Language",
    d: "Hypertext Markup Language",
    ans: "ans4",
  },
  {
    qid: "2",
    question: "Q2: What is the fullform of CSS?",
    a: "Cascading Style Sheets",
    b: "Cascading Style Sheep",
    c: "Cartoon Style Sheets",
    d: "Cascading Super Sheets",
    ans: "ans1",
  },
  {
    qid: "3",
    question: "Q3: What is the fullform of HTTP?",
    a: "Hypertext Transfer Product",
    b: "Hypertext Train Product",
    c: "Hippo Transfer Product",
    d: "Hypertext Transfer Protocol",
    ans: "ans4",
  },
  {
    qid: "4",
    question: "Q4: What is the fullform of JS?",
    a: "Java Script",
    b: "Jana Script",
    c: "Jabe Script",
    d: "Jogaru Script",
    ans: "ans1",
  },
  {
    qid: "5",
    question: "Q5: What is the fullform of IAS?",
    a: "Indian Apple Shop",
    b: "Indian Administritive Service",
    c: "Idhar Aa Saale",
    d: "Itna Accha Scooty",
    ans: "ans2",
  },
  {
    qid: "6",
    question: "Q6: What is the fullform of IAS?",
    a: "Indian Apple Shop",
    b: "Indian Administritive Service",
    c: "Idhar Aa Saale",
    d: "Itna Accha Scooty",
    ans: "ans2",
  },
  {
    qid: "7",
    question: "Q7: What is the fullform of IAS?",
    a: "Indian Apple Shop",
    b: "Indian Administritive Service",
    c: "Idhar Aa Saale",
    d: "Itna Accha Scooty",
    ans: "ans2",
  },
  {
    qid: "8",
    question: "Q8: What is the fullform of IAS?",
    a: "Indian Apple Shop",
    b: "Indian Administritive Service",
    c: "Idhar Aa Saale",
    d: "Itna Accha Scooty",
    ans: "ans2",
  },
  {
    qid: "9",
    question: "Q9: What is the fullform of IAS?",
    a: "Indian Apple Shop",
    b: "Indian Administritive Service",
    c: "Idhar Aa Saale",
    d: "Itna Accha Scooty",
    ans: "ans2",
  },
  {
    qid: "10",
    question: "Q10: What is the fullform of IAS?",
    a: "Indian Apple Shop",
    b: "Indian Administritive Service",
    c: "Idhar Aa Saale",
    d: "Itna Accha Scooty",
    ans: "ans2",
  },
  {
    qid: "11",
    question: "Q11: What is the fullform of HTML?",
    a: "Hi Text Markup Law",
    b: "Hello To My Land",
    c: "HyperText Markup Language",
    d: "Hypertext Markup Language",
    ans: "ans4",
  },
  {
    qid: "12",
    question: "Q12: What is the fullform of CSS?",
    a: "Cascading Style Sheets",
    b: "Cascading Style Sheep",
    c: "Cartoon Style Sheets",
    d: "Cascading Super Sheets",
    ans: "ans1",
  },
];